server:
    port: 8080

session:
    expiration: 30 # Session 失效时间（单位：分钟）


spring:
    profiles:
      active: dev
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    mvc:
        favicon:
          enabled: false

    application:
        name: micro-service-provider-static

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none

    datasource:
        driverClassName: org.postgresql.Driver
        druid:
            url: jdbc:postgresql://114.255.78.181:9839/pgis #?socketTimeout=1&connectTimeout=1 # 实际是 * 1000，单位：秒。socket操作（读写）超时，单位：毫秒。 0表示永不超时；和数据库服务器建立socket连接时的超时，单位：毫秒。 0表示永不超时，适用于JDK 1.4及更高版本
            username: pgis
            password: pgis_igoosd.com_402
            type: com.alibaba.druid.pool.DruidDataSource
            initialSize: 10 # 初始化连接个数
            minIdle: 10 # 连接池最小个数
            maxActive: 100 # 连接池最大个数--已过期 不在使用
            maxWait: 60000 # 获取连接等待超时的时间，单位：毫秒
            timeBetweenEvictionRunsMillis: 90000 #60s间隔
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20

    redis:
        database: 1  # 生产环境实例
        host: 114.255.78.181
        port: 6666
        password: Zycj64671537

        pool:
            max-idle: 20
            min-idle: 0
            max-active: 18
            max-wait: -1
        timeout: 0


    freemarker:
        suffix: .html
        cache: false
        charset: UTF-8
        allowRequestOverride: false
        allowSessionOverride: false
        checkTemplateLocation: false
        contentType: text/html
        exposeRequestAttributes: true # 设定所有request的属性在merge到模板的时候，是否要都添加到model中
        exposeSessionAttributes: false # 设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中
        templateEncoding: UTF-8
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true
            locale: zh_CN
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
            datetime_format: yyyy-MM-dd HH:mm:ss
            auto_import: spring.ftl as s

    devtools:
        restart:
#            additional-paths: target/classes/
            additional-paths: micro-service-provider/micro-service-provider-static/target/classes/

logging:
#    file: /Users/young/Desktop/pgis.log
    level:
        ROOT:  INFO #
#控制卡获取页面的domain
screen:
    init:
       domain: http://114.255.78.182:8080/
       warnNum: 40
# realTime Server
retrofit:
    base-url: http://114.255.78.182:15498/
    timeout: 3 #单位 s
